# .github/workflows/actions.yml

name: Github Actions로 작업 병렬로 실행하기
on: push

jobs:
  build:
    runs-on: ubuntu-latest # 리눅스에서 빌드
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: npm run build

  test_windows:
    needs: build
    runs-on: windows-latest # 윈도우에서 테스트
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: npm run build

  test_mac:
    needs: build
    runs-on: macos-latest # 맥에서도 테스트
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: npm run build
